# fly.toml app configuration file generated for pdfmathtranslate-next on 2025-10-02T17:19:04Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pdfmathtranslate-next'
primary_region = 'sin'

[env]
  PDF2ZH_API_MAX_CONCURRENCY = '1'
  PDF2ZH_API_WORKERS = '1'
  PDF2ZH_POOL_MAX_WORKERS = '1'
  PDF2ZH_QPS = '1'
  ORT_TENSORRT_ENGINE_CACHE_ENABLE = '0'
  CUDA_VISIBLE_DEVICES = ''
  NVIDIA_VISIBLE_DEVICES = ''
  # Disable ONNX Runtime GPU detection completely
  ORT_DISABLE_ALL = '1'
  ORT_CPU_ONLY = '1'
  HIP_VISIBLE_DEVICES = ''
  ONEAPI_DEVICE_SELECTOR = ''
  ZES_ENABLE_SYSMAN = '0'
  # Reduce logging from ML libraries
  TOKENIZERS_PARALLELISM = 'false'
  TRANSFORMERS_OFFLINE = '1'
  HF_HUB_OFFLINE = '1'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = "60s"
    timeout = "10s"
    grace_period = "30s"
    method = "GET"
    path = "/v1/health"

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
