# fly.toml app configuration file generated for pdfmathtranslate-next on 2025-10-02T17:19:04Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pdfmathtranslate-next'
primary_region = 'sin'

[env]
  PDF2ZH_API_MAX_CONCURRENCY = '1'
  PDF2ZH_API_WORKERS = '1'
  PDF2ZH_POOL_MAX_WORKERS = '1'
  PDF2ZH_QPS = '1'
  ORT_TENSORRT_ENGINE_CACHE_ENABLE = '0'
  CUDA_VISIBLE_DEVICES = ''
  NVIDIA_VISIBLE_DEVICES = ''

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = "60s"
    timeout = "10s"
    grace_period = "30s"
    method = "GET"
    path = "/v1/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
