name: Docker Build Only

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
        default: 'latest'
      push_to_acr:
        description: 'Push to Aliyun ACR'
        required: false
        type: boolean
        default: true

jobs:
  build-docker:
    uses: ./.github/workflows/docker-build.yml
    with:
      version: ${{ github.event.inputs.version }}
      is_release: ${{ github.event.inputs.version != 'latest' }}
      push_to_acr: ${{ github.event.inputs.push_to_acr }}
    secrets: inherit